apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  ports:
    - port: 80
      name: http
      targetPort: frontend-port
      protocol: TCP
  selector:
    app: frontend
  type: ClusterIP