apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/issuer: letsencrypt-staging
  name: ingress-nginx
  namespace: prod
spec:
  ingressClassName: nginx
  rules:
    - host: www.pvtcwd.com
      http:
        paths:
          - backend:
              service:
                name: app-service
                port:
                  number: 80
            path: /
            pathType: Prefix
          - backend:
              service:
                name: backend
                port:
                  number: 8888
            path: /api
            pathType: Prefix
  tls:
    - hosts:
        - www.pvtcwd.com
      secretName: certssl